Appitzr-Project/Frontend

- src/components/Venue/MenuOption.js
**revisi ui - add logout pop up**
trello: https://trello.com/c/TL2L1MtM/6-ui-venue-owner-menu-options
> add logout popup in venue/menuOption

- src/components/Member/Profile/components/ConfirmationDialog.js
- src/components/Member/Profile/index.js
> add dialog for logout

- src/components/Member/Profile/index.js
- src/components/Scan/index.js
Bug fixes 
No: 10 & 15
https://docs.google.com/spreadsheets/d/18YNvJacvhViOu3y4R5qv4B1cTrv4U6b1vd7hOYBh4aA/edit#gid=0
> fix(member): profile + scan

- src/components/ProfileEdit/index.jsx
> feat: Add back push to member page

- src/App.js
- src/components/Member/Home/index.js
- src/components/Venue/index.js
Casenya sekarang
1. Kalau member belum jadi venue, ketika klik icon toko diarahkan ke => https://dev.appetizr.co/venue/profile
2. Kalau member udah jadi venue, ketika klik icon toko diarahkan ke => https://dev.appetizr.co/venue
3. Ketika login, dan member sudah jadi venue, maka diarahkan ke => https://dev.appetizr.co/venue secara automatis
Nomor 1 sudah di kerjakan, nomor 2 dan 3 belum
> Member venue switch

- src/components/Member/Home/index.js
1. Ketika login / register by google, header icon mengarah ke venue, padahal di group belum ada group venue
> Update Member Home Index - Header Cart Button to Venue

- src/components/Venue/Menu/components/MenuCard.js
- src/components/Venue/Menu/components/MenuList.js
- src/components/Venue/Menu/index.js
- src/components/Venue/index.js
fix menu image in  /venue/menu/list
> fix image in venue/menu/list

- src/components/Venue/MenuForm/components/SelectOption.js
- src/components/Venue/MenuForm/edit.js
- src/components/Venue/MenuForm/index.js
- src/components/Venue/MenuForm/utils/strings.js
- src/components/Venue/index.js
- src/helpers/helper.js
- src/redux/api/venue.api.js
url: /venue/menu/edit/:menuId
task: https://trello.com/c/f9m2h195/41-api-venuemenuadd
> feat: Add integrate venue edit delete

- src/components/Venue/MenuForm/components/InputForm.js
- src/components/Venue/MenuForm/edit.js
- src/components/Venue/MenuForm/index.js
url: /venu/menu/edit/:menuId, /venu/menu/add
> fix: Fix input type menu add edit

- src/components/Venue/Menu/components/MenuList.js
- src/components/Venue/Menu/index.js
- src/components/Venue/index.js
fix small bug 
* show more in venue/menu/list
remove warning in venue/index
> fix show more in venue/menu/list

- src/components/Member/OrderHistory/MenuCard.jsx
- src/components/Member/OrderHistory/OrderHistory.jsx
Update Menu card dari tampilan menu order history dari pull request https://github.com/Appitzr-Project/Frontend/pull/59
> Update tampilan menu list order history

- src/App.js
- src/components/Authenticator/ForgotPassword.jsx
- src/components/Authenticator/Register.jsx
- src/components/Member/Home/index.js
- src/components/Member/Profile/components/ConfirmationDialog.js
- src/components/Member/index.js
- src/components/Venue/MenuOption.js
- src/components/Venue/index.js
- src/redux/actions/auth.action.js
- src/redux/api/auth.api.js
trello : https://trello.com/c/xrfHbi6x/44-integrasi-amplify-forget-password
route : /forgot-password
changes :  add feature forgot password and fix double router
> add fitur forgot password and fix  double  router

- src/components/Authenticator/ConfirmationCode.jsx
- src/components/Authenticator/ForgotPassword.jsx
- src/components/Authenticator/Login.jsx
- src/components/Authenticator/Register.jsx
- src/components/Member/Home/index.js
- src/components/Member/OrderMenu/components/MenuCard.js
- src/components/Member/OrderMenu/components/MenuItem.js
- src/components/Member/OrderMenu/index.js
- src/components/Member/index.js
- src/components/Venue/Detail/index.js
- src/components/Venue/MenuForm/edit.js
- src/components/Venue/Profile/Profile.jsx
- src/components/Venue/index.js
- src/redux/actions/auth.action.js
tast trello : 
https://trello.com/c/6rkBuJzx/45-redirect-menu-sering-blank-page
https://trello.com/c/MlF6Ny5k/51-ui-ubah-title-pada-screen-login-dan-registerasi-menjadi-appetizrco
> change title di ui (login , register , forgot psw, confirm code ), refactor warning code, and also fix redirect login google

- src/components/Card/components/CategoryCard/index.js
- src/components/Card/components/VenueCard/index.js
Resolve: #66
Task: https://trello.com/c/uigeGIYJ/66-create-react-component-for-venue-list-create-category-card-venue-card-component
> feat: Add card category and venue on venue list

- package.json
- src/App.js
- src/components/CheckBox/CheckBox.jsx
- src/components/CheckBox/FilterBox.js
1. create checkbox component
2. create filter component: included checkbox component
3. add icons from react - icons
> add Filter and Checkbox component

- src/components/Card/components/OrderSummaryCard/MenuList.js
- src/components/Card/components/OrderSummaryCard/index.js
> order summary card

- package.json
- public/index.html
- src/App.js
- src/components/Card/components/VenueCard/index.js
- src/components/CheckBox/FilterBox.js
- src/routes/VenueList/index.js
https://trello.com/c/K492DkTa/59-convert-venue-list-to-use-fooyes-template
> convert venue list to fooyes template

- .github/workflows/codeql-analysis.yml
- .gitignore
- amplify.yml
- package-lock.json
- src/components/Footer/index.jsx
- src/components/MenuList/components/MenuListContentContainer/index.js
- src/components/NavBar/index.jsx
1. Deploy Gagal, Log terakhir dibawah
```
2021-05-17T10:41:23.389Z [INFO]: $ react-scripts build
2021-05-17T10:41:24.784Z [INFO]: Creating an optimized production build...
2021-05-17T10:43:12.315Z [INFO]: Compiled with warnings.
```
2. Deploy di local pc ga ada masalah, cuma error warning nya memang banyak, ga tau kalau ini pengaruh atau gak, yg buat deploy gagal
3. Aq push package-lock.json juga biar package nya ga keinstall versi baru terus, jadi sesuai di package-lock.json 
4. Deployer Cache node_modules skip dulu, mau liat perbedaan deploy nya
> Fix error build 20210517

- package-lock.json
- package.json
- src/components/Member/Home/HomePage.jsx
- src/components/NavBar/index.jsx
- src/components/Venue/Profile/Profile.jsx
- src/components/Venue/Profile/ProfileStyle.js
- src/redux/actions/auth.action.js
https://trello.com/c/lcQtIqKO/85-added-access-to-register-as-a-venue
https://trello.com/c/OJgyTzqM/102-change-template-venue-profile-to-fooyes-theme
https://trello.com/c/rqlttr48/96-homepage-none-of-these-links-go-anywhere
> remove die link on header, add barcode, change tempate in profil venue

- src/components/Authenticator/ConfirmationCodeTemplate.jsx
- src/components/Authenticator/Register.jsx
1. fixing tampilan confirmation code
2. display email on textbox
> fixing bug confirmation code

- src/components/CheckBox/FilterBox.js
- src/components/MenuList/components/MenuListBanner/index.js
- src/routes/VenueList/index.js
- hide element map in venue list 
- integrated categories in venue list
- show banner in menu list
> Hide el and show banner in menulist
